# PowerAutomation 4.0 - 录制即测试配置文件
# Record-as-Test Configuration for ClaudEditor 4.1

record_as_test:
  # 录制设置
  recording:
    auto_start: false                    # 是否自动开始录制
    video_quality: "high"                # 视频质量: low, medium, high
    screenshot_interval: 1000            # 截图间隔(毫秒)
    max_session_duration: 3600           # 最大会话时长(秒)
    capture_mouse_movements: true        # 是否捕获鼠标移动
    capture_keyboard_events: true        # 是否捕获键盘事件
    capture_network_requests: false      # 是否捕获网络请求
    
  # 测试生成设置
  test_generation:
    auto_generate: true                  # 录制结束后自动生成测试
    include_screenshots: true            # 测试中包含截图
    include_video: true                  # 测试中包含视频
    ai_optimization: true                # 启用AI优化
    smart_assertions: true               # 智能断言生成
    test_framework: "pytest"             # 测试框架: pytest, unittest
    
  # 浏览器设置
  browser:
    headless: false                      # 是否无头模式
    window_size: [1920, 1080]           # 窗口大小
    user_agent: "ClaudEditor-RecordAsTest/4.1"
    timeout: 30                          # 操作超时时间(秒)
    implicit_wait: 10                    # 隐式等待时间(秒)
    page_load_timeout: 30                # 页面加载超时(秒)
    
  # AI集成设置
  ai:
    claude_model: "claude-3-sonnet-20240229"  # Claude模型
    optimization_enabled: true           # 启用AI优化
    smart_assertions: true               # 智能断言
    code_review: true                    # AI代码审查
    performance_suggestions: true        # 性能建议
    max_tokens: 4000                     # 最大token数
    temperature: 0.7                     # 创造性参数
    
  # 存储设置
  storage:
    recordings_path: "./recordings"      # 录制文件存储路径
    tests_path: "./generated_tests"      # 生成测试存储路径
    videos_path: "./videos"              # 视频文件存储路径
    screenshots_path: "./screenshots"    # 截图存储路径
    max_storage_size: "10GB"             # 最大存储大小
    auto_cleanup_days: 30                # 自动清理天数
    
  # 回放设置
  playback:
    speed_multiplier: 1.0                # 回放速度倍数
    pause_on_error: true                 # 错误时暂停
    screenshot_on_error: true            # 错误时截图
    retry_failed_steps: 3                # 失败步骤重试次数
    step_delay: 500                      # 步骤间延迟(毫秒)
    
  # 集成设置
  integration:
    stagewise_enabled: true              # 启用Stagewise集成
    memoryos_enabled: true               # 启用MemoryOS集成
    claudeditor_integration: true        # ClaudEditor集成
    export_formats: ["python", "json", "yaml"]  # 导出格式
    
  # 通知设置
  notifications:
    recording_started: true              # 录制开始通知
    recording_stopped: true              # 录制结束通知
    test_generated: true                 # 测试生成通知
    optimization_completed: true         # 优化完成通知
    playback_finished: true              # 回放完成通知
    
  # 安全设置
  security:
    mask_sensitive_data: true            # 遮蔽敏感数据
    exclude_password_fields: true        # 排除密码字段
    sanitize_urls: true                  # 清理URL中的敏感信息
    encrypt_recordings: false            # 加密录制文件
    
  # 性能设置
  performance:
    max_concurrent_recordings: 5         # 最大并发录制数
    memory_limit: "2GB"                  # 内存限制
    cpu_limit: 80                        # CPU使用限制(%)
    disk_space_threshold: "1GB"          # 磁盘空间阈值
    
  # 调试设置
  debug:
    log_level: "INFO"                    # 日志级别
    save_debug_info: false               # 保存调试信息
    verbose_output: false                # 详细输出
    performance_monitoring: true         # 性能监控
    
  # 实验性功能
  experimental:
    ai_action_prediction: false          # AI动作预测
    smart_element_detection: true        # 智能元素检测
    auto_test_maintenance: false         # 自动测试维护
    cross_browser_testing: false         # 跨浏览器测试

# ClaudEditor 4.1 特定配置
claudeditor:
  # UI集成
  ui_integration:
    show_recording_panel: true           # 显示录制面板
    show_test_panel: true                # 显示测试面板
    show_playback_panel: true            # 显示回放面板
    toolbar_integration: true            # 工具栏集成
    
  # 快捷键
  shortcuts:
    start_recording: "Ctrl+Shift+R"      # 开始录制
    stop_recording: "Ctrl+Shift+S"       # 停止录制
    generate_test: "Ctrl+Shift+G"        # 生成测试
    playback_test: "Ctrl+Shift+P"        # 回放测试
    optimize_test: "Ctrl+Shift+O"        # 优化测试
    
  # 菜单集成
  menu_integration:
    record_menu: true                    # 录制菜单
    test_menu: true                      # 测试菜单
    tools_menu: true                     # 工具菜单
    help_menu: true                      # 帮助菜单

# 平台特定配置
platform:
  # macOS配置
  macos:
    use_native_notifications: true       # 使用原生通知
    dock_integration: true               # Dock集成
    menu_bar_integration: true           # 菜单栏集成
    
  # Windows配置
  windows:
    use_native_notifications: true       # 使用原生通知
    taskbar_integration: true            # 任务栏集成
    system_tray_integration: true        # 系统托盘集成
    
  # Linux配置
  linux:
    use_native_notifications: true       # 使用原生通知
    desktop_integration: true            # 桌面集成
    
# 开发者配置
developer:
  # API设置
  api:
    enable_rest_api: false               # 启用REST API
    api_port: 8080                       # API端口
    api_host: "localhost"                # API主机
    
  # 插件系统
  plugins:
    enable_plugins: true                 # 启用插件系统
    plugin_directory: "./plugins"        # 插件目录
    auto_load_plugins: true              # 自动加载插件

